// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: node/node/event.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "node.node";

/** Query defines the gRPC querier service. */
export interface EventPosminingCharged {
  sender: string;
  posmined: string;
}

function createBaseEventPosminingCharged(): EventPosminingCharged {
  return { sender: "", posmined: "" };
}

export const EventPosminingCharged: MessageFns<EventPosminingCharged> = {
  encode(message: EventPosminingCharged, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sender !== "") {
      writer.uint32(10).string(message.sender);
    }
    if (message.posmined !== "") {
      writer.uint32(18).string(message.posmined);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventPosminingCharged {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventPosminingCharged();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sender = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.posmined = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventPosminingCharged {
    return {
      sender: isSet(object.sender) ? globalThis.String(object.sender) : "",
      posmined: isSet(object.posmined) ? globalThis.String(object.posmined) : "",
    };
  },

  toJSON(message: EventPosminingCharged): unknown {
    const obj: any = {};
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    if (message.posmined !== "") {
      obj.posmined = message.posmined;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventPosminingCharged>, I>>(base?: I): EventPosminingCharged {
    return EventPosminingCharged.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventPosminingCharged>, I>>(object: I): EventPosminingCharged {
    const message = createBaseEventPosminingCharged();
    message.sender = object.sender ?? "";
    message.posmined = object.posmined ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
