// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: node/node/posmining.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Coin } from "../../cosmos/base/v1beta1/coin";

export const protobufPackage = "node.node";

export interface Posmining {
  owner: string;
  coin: Coin | undefined;
  lastTransaction: string;
}

function createBasePosmining(): Posmining {
  return { owner: "", coin: undefined, lastTransaction: "" };
}

export const Posmining: MessageFns<Posmining> = {
  encode(message: Posmining, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.owner !== "") {
      writer.uint32(10).string(message.owner);
    }
    if (message.coin !== undefined) {
      Coin.encode(message.coin, writer.uint32(18).fork()).join();
    }
    if (message.lastTransaction !== "") {
      writer.uint32(26).string(message.lastTransaction);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Posmining {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePosmining();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.coin = Coin.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastTransaction = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Posmining {
    return {
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      coin: isSet(object.coin) ? Coin.fromJSON(object.coin) : undefined,
      lastTransaction: isSet(object.lastTransaction) ? globalThis.String(object.lastTransaction) : "",
    };
  },

  toJSON(message: Posmining): unknown {
    const obj: any = {};
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.coin !== undefined) {
      obj.coin = Coin.toJSON(message.coin);
    }
    if (message.lastTransaction !== "") {
      obj.lastTransaction = message.lastTransaction;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Posmining>, I>>(base?: I): Posmining {
    return Posmining.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Posmining>, I>>(object: I): Posmining {
    const message = createBasePosmining();
    message.owner = object.owner ?? "";
    message.coin = (object.coin !== undefined && object.coin !== null) ? Coin.fromPartial(object.coin) : undefined;
    message.lastTransaction = object.lastTransaction ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
