// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package node

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_CoinsPerTime        protoreflect.MessageDescriptor
	fd_CoinsPerTime_day    protoreflect.FieldDescriptor
	fd_CoinsPerTime_hour   protoreflect.FieldDescriptor
	fd_CoinsPerTime_minute protoreflect.FieldDescriptor
	fd_CoinsPerTime_second protoreflect.FieldDescriptor
)

func init() {
	file_node_node_coins_per_time_proto_init()
	md_CoinsPerTime = File_node_node_coins_per_time_proto.Messages().ByName("CoinsPerTime")
	fd_CoinsPerTime_day = md_CoinsPerTime.Fields().ByName("day")
	fd_CoinsPerTime_hour = md_CoinsPerTime.Fields().ByName("hour")
	fd_CoinsPerTime_minute = md_CoinsPerTime.Fields().ByName("minute")
	fd_CoinsPerTime_second = md_CoinsPerTime.Fields().ByName("second")
}

var _ protoreflect.Message = (*fastReflection_CoinsPerTime)(nil)

type fastReflection_CoinsPerTime CoinsPerTime

func (x *CoinsPerTime) ProtoReflect() protoreflect.Message {
	return (*fastReflection_CoinsPerTime)(x)
}

func (x *CoinsPerTime) slowProtoReflect() protoreflect.Message {
	mi := &file_node_node_coins_per_time_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_CoinsPerTime_messageType fastReflection_CoinsPerTime_messageType
var _ protoreflect.MessageType = fastReflection_CoinsPerTime_messageType{}

type fastReflection_CoinsPerTime_messageType struct{}

func (x fastReflection_CoinsPerTime_messageType) Zero() protoreflect.Message {
	return (*fastReflection_CoinsPerTime)(nil)
}
func (x fastReflection_CoinsPerTime_messageType) New() protoreflect.Message {
	return new(fastReflection_CoinsPerTime)
}
func (x fastReflection_CoinsPerTime_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_CoinsPerTime
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_CoinsPerTime) Descriptor() protoreflect.MessageDescriptor {
	return md_CoinsPerTime
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_CoinsPerTime) Type() protoreflect.MessageType {
	return _fastReflection_CoinsPerTime_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_CoinsPerTime) New() protoreflect.Message {
	return new(fastReflection_CoinsPerTime)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_CoinsPerTime) Interface() protoreflect.ProtoMessage {
	return (*CoinsPerTime)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_CoinsPerTime) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Day != "" {
		value := protoreflect.ValueOfString(x.Day)
		if !f(fd_CoinsPerTime_day, value) {
			return
		}
	}
	if x.Hour != "" {
		value := protoreflect.ValueOfString(x.Hour)
		if !f(fd_CoinsPerTime_hour, value) {
			return
		}
	}
	if x.Minute != "" {
		value := protoreflect.ValueOfString(x.Minute)
		if !f(fd_CoinsPerTime_minute, value) {
			return
		}
	}
	if x.Second != "" {
		value := protoreflect.ValueOfString(x.Second)
		if !f(fd_CoinsPerTime_second, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_CoinsPerTime) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "node.node.CoinsPerTime.day":
		return x.Day != ""
	case "node.node.CoinsPerTime.hour":
		return x.Hour != ""
	case "node.node.CoinsPerTime.minute":
		return x.Minute != ""
	case "node.node.CoinsPerTime.second":
		return x.Second != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: node.node.CoinsPerTime"))
		}
		panic(fmt.Errorf("message node.node.CoinsPerTime does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CoinsPerTime) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "node.node.CoinsPerTime.day":
		x.Day = ""
	case "node.node.CoinsPerTime.hour":
		x.Hour = ""
	case "node.node.CoinsPerTime.minute":
		x.Minute = ""
	case "node.node.CoinsPerTime.second":
		x.Second = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: node.node.CoinsPerTime"))
		}
		panic(fmt.Errorf("message node.node.CoinsPerTime does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_CoinsPerTime) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "node.node.CoinsPerTime.day":
		value := x.Day
		return protoreflect.ValueOfString(value)
	case "node.node.CoinsPerTime.hour":
		value := x.Hour
		return protoreflect.ValueOfString(value)
	case "node.node.CoinsPerTime.minute":
		value := x.Minute
		return protoreflect.ValueOfString(value)
	case "node.node.CoinsPerTime.second":
		value := x.Second
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: node.node.CoinsPerTime"))
		}
		panic(fmt.Errorf("message node.node.CoinsPerTime does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CoinsPerTime) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "node.node.CoinsPerTime.day":
		x.Day = value.Interface().(string)
	case "node.node.CoinsPerTime.hour":
		x.Hour = value.Interface().(string)
	case "node.node.CoinsPerTime.minute":
		x.Minute = value.Interface().(string)
	case "node.node.CoinsPerTime.second":
		x.Second = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: node.node.CoinsPerTime"))
		}
		panic(fmt.Errorf("message node.node.CoinsPerTime does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CoinsPerTime) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "node.node.CoinsPerTime.day":
		panic(fmt.Errorf("field day of message node.node.CoinsPerTime is not mutable"))
	case "node.node.CoinsPerTime.hour":
		panic(fmt.Errorf("field hour of message node.node.CoinsPerTime is not mutable"))
	case "node.node.CoinsPerTime.minute":
		panic(fmt.Errorf("field minute of message node.node.CoinsPerTime is not mutable"))
	case "node.node.CoinsPerTime.second":
		panic(fmt.Errorf("field second of message node.node.CoinsPerTime is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: node.node.CoinsPerTime"))
		}
		panic(fmt.Errorf("message node.node.CoinsPerTime does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_CoinsPerTime) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "node.node.CoinsPerTime.day":
		return protoreflect.ValueOfString("")
	case "node.node.CoinsPerTime.hour":
		return protoreflect.ValueOfString("")
	case "node.node.CoinsPerTime.minute":
		return protoreflect.ValueOfString("")
	case "node.node.CoinsPerTime.second":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: node.node.CoinsPerTime"))
		}
		panic(fmt.Errorf("message node.node.CoinsPerTime does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_CoinsPerTime) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in node.node.CoinsPerTime", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_CoinsPerTime) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_CoinsPerTime) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_CoinsPerTime) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_CoinsPerTime) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*CoinsPerTime)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Day)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Hour)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Minute)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Second)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*CoinsPerTime)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Second) > 0 {
			i -= len(x.Second)
			copy(dAtA[i:], x.Second)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Second)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Minute) > 0 {
			i -= len(x.Minute)
			copy(dAtA[i:], x.Minute)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Minute)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Hour) > 0 {
			i -= len(x.Hour)
			copy(dAtA[i:], x.Hour)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Hour)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Day) > 0 {
			i -= len(x.Day)
			copy(dAtA[i:], x.Day)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Day)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*CoinsPerTime)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: CoinsPerTime: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: CoinsPerTime: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Day", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Day = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Hour", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Hour = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Minute", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Minute = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Second", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Second = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: node/node/coins_per_time.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoinsPerTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day    string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Hour   string `protobuf:"bytes,2,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute string `protobuf:"bytes,3,opt,name=minute,proto3" json:"minute,omitempty"`
	Second string `protobuf:"bytes,4,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *CoinsPerTime) Reset() {
	*x = CoinsPerTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_node_coins_per_time_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinsPerTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinsPerTime) ProtoMessage() {}

// Deprecated: Use CoinsPerTime.ProtoReflect.Descriptor instead.
func (*CoinsPerTime) Descriptor() ([]byte, []int) {
	return file_node_node_coins_per_time_proto_rawDescGZIP(), []int{0}
}

func (x *CoinsPerTime) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *CoinsPerTime) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

func (x *CoinsPerTime) GetMinute() string {
	if x != nil {
		return x.Minute
	}
	return ""
}

func (x *CoinsPerTime) GetSecond() string {
	if x != nil {
		return x.Second
	}
	return ""
}

var File_node_node_coins_per_time_proto protoreflect.FileDescriptor

var file_node_node_coins_per_time_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x63, 0x6f, 0x69, 0x6e,
	0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x64, 0x0a, 0x0c, 0x43,
	0x6f, 0x69, 0x6e, 0x73, 0x50, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x75,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x42, 0x97, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x42, 0x11, 0x43, 0x6f, 0x69, 0x6e, 0x73, 0x50, 0x65, 0x72, 0x54, 0x69, 0x6d,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x75, 0x72, 0x6f, 0x62, 0x6f, 0x72, 0x6f, 0x73, 0x2d, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e,
	0x6f, 0x64, 0x65, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0xa2, 0x02, 0x03, 0x4e, 0x4e, 0x58, 0xaa, 0x02,
	0x09, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0xca, 0x02, 0x09, 0x4e, 0x6f, 0x64,
	0x65, 0x5c, 0x4e, 0x6f, 0x64, 0x65, 0xe2, 0x02, 0x15, 0x4e, 0x6f, 0x64, 0x65, 0x5c, 0x4e, 0x6f,
	0x64, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x3a, 0x3a, 0x4e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_node_node_coins_per_time_proto_rawDescOnce sync.Once
	file_node_node_coins_per_time_proto_rawDescData = file_node_node_coins_per_time_proto_rawDesc
)

func file_node_node_coins_per_time_proto_rawDescGZIP() []byte {
	file_node_node_coins_per_time_proto_rawDescOnce.Do(func() {
		file_node_node_coins_per_time_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_node_coins_per_time_proto_rawDescData)
	})
	return file_node_node_coins_per_time_proto_rawDescData
}

var file_node_node_coins_per_time_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_node_coins_per_time_proto_goTypes = []interface{}{
	(*CoinsPerTime)(nil), // 0: node.node.CoinsPerTime
}
var file_node_node_coins_per_time_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_node_coins_per_time_proto_init() }
func file_node_node_coins_per_time_proto_init() {
	if File_node_node_coins_per_time_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_node_coins_per_time_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinsPerTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_node_coins_per_time_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_node_coins_per_time_proto_goTypes,
		DependencyIndexes: file_node_node_coins_per_time_proto_depIdxs,
		MessageInfos:      file_node_node_coins_per_time_proto_msgTypes,
	}.Build()
	File_node_node_coins_per_time_proto = out.File
	file_node_node_coins_per_time_proto_rawDesc = nil
	file_node_node_coins_per_time_proto_goTypes = nil
	file_node_node_coins_per_time_proto_depIdxs = nil
}
